security:
  oauth2:
    client:
      clientId: your-onelogin-oidc-app-client-id
      clientSecret: your-onelogin-oidc-app-client-secret
      accessTokenUri: https://<subdomain>.onelogin.com/oidc/2/token
      userAuthorizationUri: https://<subdomain>.onelogin.com/oidc/2/auth
      tokenName: access_token
      authorizedGrantTypes: authorization_code
      scope: openid,profile,email
    resource:
      userInfoUri: https://<subdomain>.onelogin.com/oidc/2/me

server:
  port : 8081
